boosthist:
  #- /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/VBSCodeNew/CoffeaTools/1Jan2023/SMQawa/data/merged-histogram-PhotonCR-2018.pkl.gz
  #- /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/VBSCodeNew/CoffeaTools/1Jan2023/SMQawa/data/merged-histogram-PhotonCR_1a-2018.pkl.gz
  - merged-histogram-PhCR-2016.pkl.gz 
  

xsections:
  !include ./config/xsections_2018_PCR.yaml

luminosity:
  # from : https://docs.google.com/presentation/d/1gEF2jExqS1hWs-dlYgxrTT2xQztYbBZcrLdw45Aiy7g/edit#slide=id.gaa4333d304_0_0
  value: 16.5
  uncer: 1.025

groups:
  #WJets:
  #  processes:
  #   #- WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8
  #   - WJetsToLNu_HT-70To100_TuneCP5_13TeV-madgraphMLM-pythia8  
  #   - WJetsToLNu_HT-100To200_TuneCP5_13TeV-madgraphMLM-pythia8
  #   - WJetsToLNu_HT-200To400_TuneCP5_13TeV-madgraphMLM-pythia8
  #   - WJetsToLNu_HT-400To600_TuneCP5_13TeV-madgraphMLM-pythia8
  #   - WJetsToLNu_HT-600To800_TuneCP5_13TeV-madgraphMLM-pythia8
  #   - WJetsToLNu_HT-800To1200_TuneCP5_13TeV-madgraphMLM-pythia8
  #   - WJetsToLNu_HT-1200To2500_TuneCP5_13TeV-madgraphMLM-pythia8
  #   - WJetsToLNu_HT-2500ToInf_TuneCP5_13TeV-madgraphMLM-pythia8
  #  type:
  #    background
  #  color:
  #    "#99B6F7"
  #ZGamma :
  #  processes:
  #    - ZGTo2NuG_TuneCP5_13TeV-amcatnloFXFX-pythia8
  #  type:
  #    background
  #  color:
  #    "#46B3A5"
  #WW:
  #  processes:
  #    - WGToLNuG_TuneCP5_13TeV-madgraphMLM-pythia8
   # type:
   #   background
   # color:
   #   "#F6D68D"
  GJets:
    processes:
      - GJets_HT-40To100_TuneCP5_13TeV-madgraphMLM-pythia8
      - GJets_HT-100To200_TuneCP5_13TeV-madgraphMLM-pythia8
      - GJets_HT-200To400_TuneCP5_13TeV-madgraphMLM-pythia8
      - GJets_HT-400To600_TuneCP5_13TeV-madgraphMLM-pythia8
      - GJets_HT-600ToInf_TuneCP5_13TeV-madgraphMLM-pythia8
    type:
      background
    color:
      "#2E6D92"
  data:
    processes:
      - SinglePhoton
    type:
      data
    color:
      "#181926"


plotting:
    photon_VBS:
        dilep_pt:
            rebin: 2 
            range: [0, 400]
            blind: false
        met_pt:
            rebin: 2 
            range: [0, 250]
            blind: false
        njets:
            rebin: 1
            range: [2, 5]
            blind: false
        bjets:
            rebin: 1
            range: [0, 5]
            blind: false
        dijet_mass:
            rebin: 2
            range: [0,2000]
            blind: false
        dijet_deta:
            rebin: 1
            range: [0, 5.5]
            blind: false
        lead_jet_pt:
            rebin: 2
            range: [30, 300]
            blind: false
        trail_jet_pt:
            rebin: 2
            range: [30, 200]
            blind: false
        lead_jet_eta:
            rebin: 2
            range: [-5,5]
            blind: false
        trail_jet_eta:
            rebin: 2
            range: [-5,5]
            blind: false
        min_dphi_met_j:
            rebin: 2
            range: [0, 2]
            blind: false
    vbs-DY:
        dilep_mt:
            rebin: 2
            range: [0, 400]
            blind: false
        dilep_pt:
            rebin: 2 
            range: [0, 400]
            blind: false
        dilep_m:
            rebin: 2 
            range: [0, 120]
            blind: false
        met_pt:
            rebin: 2 
            range: [0, 250]
            blind: false
        njets:
            rebin: 1
            range: [2, 5]
            blind: false
        bjets:
            rebin: 1
            range: [0, 5]
            blind: false
        dphi_met_ll:
            rebin: 1
            range: [1, 3.14159]
            blind: false
        gnn_score:
            rebin: 10
            range: [0, 1]
            blind: false
        gnn_flat:
            rebin: 5
            range: [0, 1]
            blind: false
        dijet_mass:
            rebin: 2
            range: [0,2000]
            blind: false
        dijet_deta:
            rebin: 1
            range: [0, 5.5]
            blind: false
        lead_jet_pt:
            rebin: 2
            range: [30, 300]
            blind: false
        trail_jet_pt:
            rebin: 1
            range: [30, 100]
            blind: false
        lead_jet_eta:
            rebin: 2
            range: [-5,5]
            blind: false
        trail_jet_eta:
            rebin: 2
            range: [-5,5]
            blind: false
        min_dphi_met_j:
            rebin: 2
            range: [0, 2]
            blind: false          
  
    vbs-TT:
        dilep_mt:
            rebin: 2
            range: [0, 400]
            blind: false
        dilep_pt:
            rebin: 2 
            range: [0, 400]
            blind: false
        dilep_m:
            rebin: 2 
            range: [0, 120]
            blind: false
        met_pt:
            rebin: 2 
            range: [0, 250]
            blind: false
        njets:
            rebin: 1
            range: [0, 5]
            blind: false
        bjets:
            rebin: 1
            range: [0, 5]
            blind: false
        dphi_met_ll:
            rebin: 2
            range: [1, 3.14159]
            blind: false
        gnn_score:
            rebin: 10
            range: [0, 1]
            blind: false
        gnn_flat:
            rebin: 5
            range: [0, 1]
            blind: false
        dijet_mass:
            rebin: 2
            range: [0,2000]
            blind: false
        dijet_deta:
            rebin: 1
            range: [0, 5.5]
            blind: false
        lead_jet_pt:
            rebin: 2
            range: [30, 300]
            blind: false
        trail_jet_pt:
            rebin: 2
            range: [30, 200]
            blind: false
        lead_jet_eta:
            rebin: 2
            range: [-5,5]
            blind: false
        trail_jet_eta:
            rebin: 2
            range: [-5,5]
            blind: false
        min_dphi_met_j:
            rebin: 2
            range: [0, 2]
            blind: false
    vbs-NR:
        dilep_mt:
            rebin: 2
            range: [0, 400]
            blind: false
        dilep_pt:
            rebin: 2 
            range: [0, 400]
            blind: false
        dilep_m:
            rebin: 2 
            range: [0, 120]
            blind: false
        met_pt:
            rebin: 2 
            range: [0, 250]
            blind: false
        njets:
            rebin: 1
            range: [0, 5]
            blind: false
        bjets:
            rebin: 1
            range: [0, 5]
            blind: false
        dphi_met_ll:
            rebin: 2
            range: [1, 3.14159]
            blind: false
        gnn_score:
            rebin: 10
            range: [0, 1]
            blind: false
        gnn_flat:
            rebin: 5
            range: [0, 1]
            blind: false
        dijet_mass:
            rebin: 2
            range: [0,2000]
            blind: false
        dijet_deta:
            rebin: 1
            range: [0, 5.5]
            blind: false
        lead_jet_pt:
            rebin: 2
            range: [30, 300]
            blind: false
        trail_jet_pt:
            rebin: 2
            range: [30, 200]
            blind: false
        lead_jet_eta:
            rebin: 2
            range: [-5,5]
            blind: false
        trail_jet_eta:
            rebin: 2
            range: [-5,5]
            blind: false
        min_dphi_met_j:
            rebin: 2
            range: [0, 2]
            blind: false
    vbs-SR:
        dilep_mt:
            rebin: 2
            range: [0, 400]
            blind: true
        dilep_pt:
            rebin: 2 
            range: [0, 400]
            blind: true
        dilep_m:
            rebin: 2 
            range: [0, 120]
            blind: true
        met_pt:
            rebin: 2 
            range: [0, 250]
            blind: true
        njets:
            rebin: 1
            range: [2, 5]
            blind: true
        bjets:
            rebin: 1
            range: [0, 5]
            blind: true
        dphi_met_ll:
            rebin: 2
            range: [1, 3.14159]
            blind: true
        gnn_score:
            rebin: 5
            range: [0, 1]
            blind: true
        gnn_flat:
            rebin: 10
            range: [0, 1]
            blind: true
        dijet_mass:
            rebin: 2
            range: [0,2000]
            blind: true
        dijet_deta:
            rebin: 1
            range: [0, 5.5]
            blind: true
        lead_jet_pt:
            rebin: 2
            range: [30, 300]
            blind: true
        trail_jet_pt:
            rebin: 2
            range: [30, 200]
            blind: true
        lead_jet_eta:
            rebin: 2
            range: [-5,5]
            blind: true
        trail_jet_eta:
            rebin: 2
            range: [-5,5]
            blind: true
        min_dphi_met_j:
            rebin: 2
            range: [0, 2]
            blind: true
    photon_VBS_2:
        dilep_pt:
            rebin: 2 
            range: [0, 400]
            blind: false
        met_pt:
            rebin: 2 
            range: [0, 250]
            blind: false
        njets:
            rebin: 1
            range: [2, 5]
            blind: false
        bjets:
            rebin: 1
            range: [0, 5]
            blind: false
        dijet_mass:
            rebin: 2
            range: [0,2000]
            blind: false
        dijet_deta:
            rebin: 1
            range: [0, 5.5]
            blind: false
        lead_jet_pt:
            rebin: 2
            range: [30, 300]
            blind: false
        trail_jet_pt:
            rebin: 2
            range: [30, 200]
            blind: false
        lead_jet_eta:
            rebin: 2
            range: [-5,5]
            blind: false
        trail_jet_eta:
            rebin: 2
            range: [-5,5]
            blind: false
        min_dphi_met_j:
            rebin: 2
            range: [0, 2]
            blind: false
    

